# Generated by Django 3.2.13 on 2022-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.CharField(max_length=45, null=True, unique=True)),
                ('expired', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bitcoin Addresses',
            },
        ),
        migrations.CreateModel(
            name='CloseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('close_registration', models.BooleanField(default=False)),
                ('custom_error_message', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Close Registration',
            },
        ),
        migrations.CreateModel(
            name='CloseWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('close_site', models.BooleanField(default=False)),
                ('closing_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Close Website',
            },
        ),
        migrations.CreateModel(
            name='VersionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('version_no', models.CharField(blank=True, max_length=25, null=True)),
                ('show_beta_icon', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Versioning',
            },
        ),
    ]
