# Generated by Django 3.2.12 on 2022-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.CharField(max_length=45, null=True, unique=True)),
                ('expired', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bitcoin Addresses',
            },
        ),
    ]
