# Generated by Django 3.2.9 on 2022-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disable_comments',
            field=models.BooleanField(null=True),
        ),
    ]
