# Generated by Django 3.2.9 on 2022-02-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220208_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disable_comments',
        ),
    ]
