# Generated by Django 3.2.9 on 2022-02-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loggedinuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disable_comments',
        ),
    ]
