# Generated by Django 3.2.12 on 2022-03-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_disable_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreUser',
        ),
        migrations.RemoveField(
            model_name='sendemail',
            name='_canned_response',
        ),
        migrations.DeleteModel(
            name='UserStatistics',
        ),
        migrations.DeleteModel(
            name='CannedResponse',
        ),
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
