# Generated by Django 3.2.13 on 2022-04-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220301_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduser',
            name='profile_update_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_update_time',
        ),
    ]
