# Generated by Django 3.2.13 on 2022-04-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220422_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduser',
            name='btc_address',
        ),
        migrations.RemoveField(
            model_name='deleteduser',
            name='pgp_fingerprint',
        ),
        migrations.RemoveField(
            model_name='deleteduser',
            name='website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='btc_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pgp_fingerprint',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
