# Generated by Django 3.2.13 on 2022-04-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220423_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='url',
        ),
        migrations.AlterField(
            model_name='userverification',
            name='verification',
            field=models.CharField(blank=True, choices=[('Fraudulent', 'Fraudulent'), ('Bot', 'Bot'), ('Official', 'Official'), ('Verified', 'Verified'), ('Out of Tune', 'Out of Tune')], max_length=100, null=True),
        ),
    ]
