# Generated by Django 3.2.13 on 2022-05-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220430_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteduser',
            name='auto_account_delete_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_account_delete_time',
        ),
    ]
