# Generated by Django 3.2.12 on 2022-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flair',
            field=models.CharField(choices=[('No Flair', 'No Flair'), ('SOS', 'SOS'), ('Whistleblowing', 'Whistleblowing')], max_length=50, null=True),
        ),
    ]
