# Generated by Django 3.2.9 on 2021-12-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20211220_1326'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='clicks',
            field=models.ManyToManyField(blank=True, related_name='clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='voucher_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.vouchers'),
        ),
    ]
