# Generated by Django 3.2.12 on 2022-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsections', '0003_remove_help_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='to_bitcoin_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
