# Generated by Django 3.2.13 on 2022-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsections', '0004_alter_ads_to_bitcoin_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='business_location',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='business_website',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='professional_email',
        ),
        migrations.AddField(
            model_name='ads',
            name='i_agree',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin')], default='1', max_length=20, null=True),
        ),
    ]
