# Generated by Django 3.2.13 on 2022-04-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsections', '0005_auto_20220423_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin')], default='Bitcoin', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='article_content',
            field=models.TextField(),
        ),
    ]
