# Generated by Django 3.2.9 on 2022-02-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211220_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentstimestamp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='mentions',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentsTimestamp',
        ),
    ]
