# Generated by Django 3.2.13 on 2022-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_flair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flair',
            field=models.CharField(choices=[('No Flair', 'No Flair'), ('Leak', 'Leak'), ('SOS', 'SOS')], max_length=50, null=True),
        ),
    ]
